export const html = `<!doctype html><html lang="ja"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>ScombZ Connector</title>
<style>:root{font-family:system-ui,-apple-system,sans-serif;color:#17324d;background:#f2f5f9;color-scheme:light}*{box-sizing:border-box}body{margin:0;padding:32px 18px}main{max-width:720px;margin:auto}h1{font-size:28px}h2{font-size:20px}p{line-height:1.8}section{background:white;padding:24px;border:1px solid #d7e0ec;border-radius:12px;margin:20px 0}input,button{font:inherit;padding:12px;max-width:100%;margin:6px 0}input[type=text],input[type=password],input[readonly]{width:100%}button{background:#173e68;border:0;color:white;border-radius:6px;cursor:pointer}button:disabled{opacity:.5}code{display:block;background:#edf2f8;padding:12px;overflow-wrap:anywhere}.muted{color:#566b81;font-size:14px}.error{color:#ac2929}[hidden]{display:none!important}a{color:#175189}</style>
<main><h1>ScombZ Connector</h1><p>あなたのCloudflareで動く、あなた専用のScombZ連携。</p>
<section><h2>管理画面を開く</h2><p id="config" role="status">サーバーの設定を確認中…</p><label for="key">Cloudflareに設定した管理キー（ADMIN_TOKEN）</label><input id="key" type="password" autocomplete="off"><button id="unlock">開く</button><button id="lock" hidden>ロックする</button><p class="muted">キーはこの画面を開いている間だけ使用します。ScombZのパスワードは入力しません。</p><p id="unlock-result" role="status"></p></section>
<section id="setup" hidden><h2>初回設定のキーを作成</h2><p>このブラウザ内でランダムなキーを生成します。CloudflareのWorker → Settings → Variables and Secretsに、2つともSecretとして保存してください。</p><button id="generate">キーを生成</button><label for="new-admin">ADMIN_TOKEN</label><input id="new-admin" type="password" readonly><label for="new-encryption">SESSION_ENCRYPTION_KEY</label><input id="new-encryption" type="password" readonly><button id="show-secrets">表示を切り替える</button><p class="muted">ADMIN_TOKENは管理画面とOAuth承認に使うため保存してください。2つとも公開しないでください。保存後にこのページを再読み込みします。</p></section><div id="private" hidden><section><h2>接続状態</h2><p id="status" role="status"></p><p><button id="relogin">再ログイン</button> <button id="revoke">ChatGPT接続を解除</button></p><details id="login-form"><summary>ログイン</summary><label for="mobile-user">学籍番号</label><input id="mobile-user" type="text" autocomplete="username"><label for="mobile-password">パスワード</label><input id="mobile-password" type="password" autocomplete="current-password"><button id="mobile-login">ログイン</button><p id="mobile-result" role="status"></p></details><details><summary>接続の管理</summary><button id="refresh">接続を確認</button><p><button id="mobile-delete">ScombZからログアウト</button></p><p><button id="delete">ScombZ認証とChatGPT接続を削除</button></p><p id="delete-result" role="status"></p></details></section></div>
<section><h2>ChatGPTに登録</h2><code id="endpoint"></code><button id="copy">MCP URLをコピー</button><p>ChatGPTでカスタムMCP接続を作成し、このURLを入力します。認証はOAuthを選びます。接続中にこのWorkerの承認ページが開いたら、管理キーを入力してください。</p><p class="muted">カスタムMCPの追加にはDeveloper modeと対応するアカウント・画面が必要です。追加項目が見つからない場合はWeb版を確認してください。</p><p>登録後の例: 「ScombZ Connectorでデータ構造とアルゴリズム2の第一回の資料を取得して」</p></section>
<section><h2>読み取れる情報</h2><p>時間割、教材、課題、アンケート、小テストの要項・公開済み結果、お知らせ。前期・後期や過去年度にも対応します。</p><p class="muted">Connectorは課題提出・受験開始・回答送信・出席送信を行いません。別途OAuthでSESSION受け渡しを承認すると、ChatGPTへWeb認証を渡し、取得・調査はChatGPT側で行えます。SESSIONは提出にも使えるため、書き込み前は毎回内容を確認してください。原本は最大100MiB。PDF・バイナリはMCP resource_linkとしてChatGPTへ渡します。</p></section></main><script src="/ui.js" defer></script></html>`;
export const script = String.raw`
const $=id=>document.getElementById(id);let key='';
const endpoint=location.origin+'/mcp';$('endpoint').textContent=endpoint;
async function api(path,options={}){const response=await fetch(path,{...options,cache:'no-store',headers:{...options.headers,Authorization:'Bearer '+key}});const result=await response.json();if(!response.ok)throw new Error(result.message||'操作を完了できません。');return result;}
function showStatus(v){$('status').textContent=v.connected?'接続済み':v.message||(v.authenticated?'接続を確認してください。':'ログインしてください。');$('status').classList.toggle('error',!v.connected);$('login-form').open=v.reauthentication_required===true||v.authenticated===false;$('relogin').textContent=v.authenticated?'再ログイン':'ログイン';}
$('unlock').onclick=async()=>{key=$('key').value;$('key').value='';try{showStatus(await api('/api/status'));$('private').hidden=false;$('lock').hidden=false;$('unlock-result').textContent='管理画面を開きました。';}catch(e){key='';$('unlock-result').textContent=e.message;}};
$('relogin').onclick=()=>{$('login-form').open=true;$('mobile-result').textContent='';$('mobile-user').focus();};
$('lock').onclick=()=>{key='';$('mobile-password').value='';$('mobile-user').value='';$('private').hidden=true;$('lock').hidden=true;$('unlock-result').textContent='ロックしました。';};
$('refresh').onclick=async()=>{try{showStatus(await api('/api/status'));}catch(e){$('status').textContent=e.message;}};
$('mobile-login').onclick=async()=>{const user=$('mobile-user').value.trim(),password=$('mobile-password').value;if(!user||!password){$('mobile-result').textContent='学籍番号とパスワードを入力してください。';return;}$('mobile-login').disabled=true;try{const result=await api('/api/mobile/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user,password})});$('mobile-password').value='';showStatus(result);$('mobile-result').textContent=result.connected?'ScombZに接続しました。':result.message||'接続を確認してください。';}catch(e){$('mobile-password').value='';$('mobile-result').textContent=e.message;}finally{$('mobile-login').disabled=false;}};
$('mobile-delete').onclick=async()=>{if(!confirm('ScombZからログアウトしますか？'))return;try{const result=await api('/api/mobile',{method:'DELETE'});showStatus({...result,authenticated:false});$('mobile-result').textContent='ログアウトしました。';}catch(e){$('mobile-result').textContent=e.message;}};
$('revoke').onclick=async()=>{if(!confirm('ChatGPTの接続をすべて解除しますか？'))return;try{await api('/api/revoke',{method:'POST'});$('delete-result').textContent='接続を解除しました。ChatGPTから再接続できます。';}catch(e){$('delete-result').textContent=e.message;}};
$('delete').onclick=async()=>{if(!confirm('ScombZ認証を削除して、ChatGPTの接続をすべて解除しますか？'))return;try{await api('/api/connection',{method:'DELETE'});$('delete-result').textContent='削除しました。';showStatus({connected:false,authenticated:false});}catch(e){$('delete-result').textContent=e.message;}};
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText(endpoint);$('copy').textContent='コピーしました';}catch{$('copy').textContent='上のURLをコピーしてください';}};
$('generate').onclick=()=>{for(const id of ['new-admin','new-encryption']){$(id).value=Array.from(crypto.getRandomValues(new Uint8Array(32)),v=>v.toString(16).padStart(2,'0')).join('');}};
$('show-secrets').onclick=()=>{for(const id of ['new-admin','new-encryption'])$(id).type=$(id).type==='password'?'text':'password';};
fetch('/health',{cache:'no-store'}).then(r=>r.json()).then(v=>{$('setup').hidden=v.configured;$('config').textContent=v.configured?'サーバーの設定を確認しました。':'CloudflareでADMIN_TOKEN・SESSION_ENCRYPTION_KEY・D1を設定してください。';}).catch(()=>{$('config').textContent='サーバーの状態を確認できません。';});
`;
